import Head from "next/head";
import Link from "next/link";
import { useAuthContext } from "@/context/AuthContext";
import Layout from "@/components/Layout";
import ProjectContextProvider from "@/context/ProjectContext";
import HomePage from "@/components/HomePage";

export default function Home() {
  const { user } = useAuthContext();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {user ? (
          <>
            <ProjectContextProvider>
              <Layout>
                <HomePage />
              </Layout>
            </ProjectContextProvider>
          </>
        ) : (
          <>
            <Link href={"/user/create"}>Sign up as a new user</Link>
            <Link href={"/user/login"}>Log in</Link>
          </>
        )}
      </main>
    </>
  );
}
